name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
      
    - name: Install dependencies
      run: make install
      
    - name: Run Pylint
      run: make lint
      
    - name: Run Pytest
      run: make test
    
    - name: Run Black
      run: make format
